# Generated by Django 4.1 on 2022-10-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_aboutus_delete_aboutas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='img',
            new_name='image',
        ),
    ]
