# Generated by Django 4.1 on 2022-08-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
