# Generated by Django 4.1 on 2022-08-27 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
