# Generated by Django 4.1 on 2022-10-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qr_code',
        ),
    ]
