# Generated by Django 4.1 on 2022-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/orders/'),
        ),
    ]
