# Generated by Django 4.1 on 2022-09-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address1',
        ),
    ]
