# Generated by Django 4.1 on 2022-08-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Rate',
        ),
    ]
