# Generated by Django 4.1 on 2022-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
