# Generated by Django 4.1 on 2022-10-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='All', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
