# Generated by Django 4.1 on 2022-10-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='describtion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
    ]
